#!/bin/ash
#
# OpenSSH

. /etc/rc.d/init.d/functions


case "$1" in
    start)
        echo -n "Starting SSH Server..."
        mkdir /var/lib/sshd
        /usr/sbin/sshd
        sleep 1
        pid=`cat /run/sshd.pid 2>/dev/null`
        echo "-16" >/proc/${pid}/oom_score_adj
        ;;

    stop)
        log_info_msg "Stopping SSH Server..."
        killproc -p "/run/sshd.pid" /usr/sbin/sshd
        ;;

    reload)
        echo -n "Reloading SSH Server..."
        pid=`cat /run/sshd.pid 2>/dev/null`
        if [ -n "${pid}" ]; then
           kill -HUP "${pid}"
        else
           (exit 1)
        fi
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;

    status)
        pid=`cat /run/sshd.pid 2>/dev/null`
        if [ -r "$pid" ]; then
            echo "Service hostapd running (PID $(cat "$pid"))."
        else
            echo "Service hostapd not running."
        fi
        ;;

    *)
        echo "Usage: $0 {start|stop|reload|restart|status}"
        exit 1
        ;;
esac